version: '3'

services:
    api:
        image: api:latest
        restart: always
        environment:
            PORT: 3001
        ports:
            - 3001:3001
    front:
        image: front:latest
        environment:
            REACT_APP_PROXY_API: http://localhost:3001/
            PORT: 3000
        ports:
            - 3000:3000
